### ISSUE TITLE
插入图片后关闭Activity报Activity has leaked window

### ISSUE THREAD

**Issue by linceln** [mr5/icarus-android#21]
```
 E/WindowManager: android.view.WindowLeaked: Activity com.olsplus.balancemall.app.merchant.goods.RichTextActivity has leaked window android.widget.PopupWindow$PopupDecorView{24829e V.E...... ......ID 0,0-53,63} that was originally added here
                                                                            at android.view.ViewRootImpl.<init>(ViewRootImpl.java:417)
                                                                            at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:331)
                                                                            at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:93)
                                                                            at android.widget.PopupWindow.invokePopup(PopupWindow.java:1380)
                                                                            at android.widget.PopupWindow.showAtLocation(PopupWindow.java:1156)
                                                                            at android.widget.PopupWindow.showAtLocation(PopupWindow.java:1119)
                                                                            at org.chromium.content.browser.input.PopupTouchHandleDrawable.show(PopupTouchHandleDrawable.java:455)
                                                                            at org.chromium.android_webview.AwContents.nativeOnDraw(Native Method)
                                                                            at org.chromium.android_webview.AwContents.access$4700(AwContents.java:100)
                                                                            at org.chromium.android_webview.AwContents$AwViewMethodsImpl.onDraw(AwContents.java:3000)
                                                                            at com.android.webview.chromium.WebViewChromium.onDraw(WebViewChromium.java:31329)
                                                                            at android.webkit.WebView.onDraw(WebView.java:2534)
                                                                            at android.view.View.draw(View.java:17070)
                                                                            at android.view.View.updateDisplayListIfDirty(View.java:16052)
                                                                            at android.view.View.draw(View.java:16836)
                                                                            at android.view.ViewGroup.drawChild(ViewGroup.java:3764)
                                                                            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3550)
                                                                            at android.view.View.updateDisplayListIfDirty(View.java:16047)
                                                                            at android.view.View.draw(View.java:16836)
                                                                            at android.view.ViewGroup.drawChild(ViewGroup.java:3764)
                                                                            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3550)
                                                                            at android.view.View.updateDisplayListIfDirty(View.java:16047)
                                                                            at android.view.View.draw(View.java:16836)
                                                                            at android.view.ViewGroup.drawChild(ViewGroup.java:3764)
                                                                            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3550)
                                                                            at android.view.View.updateDisplayListIfDirty(View.java:16047)
                                                                            at android.view.View.draw(View.java:16836)
                                                                            at android.view.ViewGroup.drawChild(ViewGroup.java:3764)
                                                                            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3550)
                                                                            at android.view.View.updateDisplayListIfDirty(View.java:16047)
                                                                            at android.view.View.draw(View.java:16836)
                                                                            at android.view.ViewGroup.drawChild(ViewGroup.java:3764)
                                                                            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3550)
                                                                            at android.view.View.updateDisplayListIfDirty(View.java:16047)
                                                                            at android.view.View.draw(View.java:16836)
                                                                            at android.view.ViewGroup.drawChild(ViewGroup.java:3764)
                                                                            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3550)
                                                                            at android.view.View.draw(View.java:17073)
                                                                            at com.android.internal.policy.DecorView.draw(DecorView.java:751)
                                                                            at android.view.View.updateDisplayListIfDirty(View.java:16052)
                                                                            at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:656)
                                                                            at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:662)
                                                                            at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:770)
                                                                            at android.view.ViewRootImpl.draw(ViewRootImpl.java:2796)
                                                                            at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2604)
                                                                            at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2211)
                                                                            at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1246)
                                                                            at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6301)
                                                                            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:871)
                                                                            at android.view.Choreographer.doCallbacks(Choreographer.java:683)
                                                                            at android.view.Choreographer.doFrame(Choreographer.java:619)
                                                                            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:857)
                                                                            at android.os.Handler.handleCallback(Handler.java:751)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                            at android.os.Looper.loop(Looper.java:154)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:6077)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
```

**Comment by Leifzhang** [comment]
you  need close all you dialog or popwindow when activity finish

**Comment by linceln** [comment]
i don't have any dialog or popup window in the activity,  only a webview

**Comment by chuwe1** [comment]
webView.destory(); @linceln

**Comment by linceln** [comment]
Thanks, it works.
